stages:
  - build
linux:
  stage: build
  tags:
    - qtdeploy
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_FORCE_HTTPS: "true"
  script:
    - cmake -B build -S . -DCMAKE_PREFIX_PATH=${CI_QT_PATH}
    - cmake --build build -j$(nproc) -- 2> ./build/log_build.txt
    - cmake --build build --target deployment
  artifacts:
    paths:
      - ./build/deployment/
    expire_in: 1 week
