stages:
  - build_linux
  - build_windows
linux:
  stage: build_linux
  tags:
    - qtdeploy
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_FORCE_HTTPS: "true"
  script:
    - cmake -B build/linux -S . -DCMAKE_PREFIX_PATH=${CI_QT_PATH} -DCI_TOOLS_PATH=${CI_TOOLS_PATH}
    - cmake --build build/linux -j$(nproc) --
    - cmake --build build/linux --target deployment
  artifacts:
    paths:
      - ./build/linux/deployment/
    expire_in: 1 week
windows:
  stage: build_windows
  tags:
    - qtdeploy
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_FORCE_HTTPS: "true"
  script:
    - cmake -B build/windows -S . -DCMAKE_TOOLCHAIN_FILE=./cmake/gitlab-mingw-share.cmake -DCI_MXE_PATH=${CI_MXE_PATH} -DENABLE_CJSON_TEST=OFF
    - cmake --build build/windows --target all install deployment
    - cmake --build build/windows --target deployment # bug this command copy all file just on second iteration 
  artifacts:
    paths:
      - ./build/windows/stplot/
    expire_in: 1 week
